apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-order
  namespace: smartlogix
  labels:
    app.kubernetes.io/name: ms-order
    app.kubernetes.io/part-of: smartlogix
    app.kubernetes.io/component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ms-order
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ms-order
        app.kubernetes.io/part-of: smartlogix
        app.kubernetes.io/component: backend
    spec:
      containers:
        - name: ms-order
          image: smartlogix/ms-order:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: POSTGRES_PEDIDO_DB
              valueFrom:
                configMapKeyRef:
                  name: smartlogix-config
                  key: POSTGRES_PEDIDO_DB
            - name: SERVER_PORT
              value: "8080"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://db-order:5432/$(POSTGRES_PEDIDO_DB)
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: smartlogix-config
                  key: POSTGRES_PEDIDO_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smartlogix-secret
                  key: POSTGRES_PEDIDO_PASSWORD
            - name: MS_INVENTORY_URL
              valueFrom:
                configMapKeyRef:
                  name: smartlogix-config
                  key: MS_INVENTORY_URL
            - name: SENTRY_DSN
              valueFrom:
                configMapKeyRef:
                  name: smartlogix-config
                  key: MS_ORDER_DSN
                  optional: true
          resources:
            requests:
              cpu: 100m
              memory: 384Mi
            limits:
              cpu: 1000m
              memory: 768Mi
