apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: smartlogix
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: smartlogix
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: frontend
  ports:
    - name: http
      port: 80
      targetPort: http
