apiVersion: v1
kind: Service
metadata:
  name: bff
  namespace: smartlogix
  labels:
    app.kubernetes.io/name: bff
    app.kubernetes.io/part-of: smartlogix
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: bff
  ports:
    - name: http
      port: 3000
      targetPort: http
