apiVersion: v1
kind: Service
metadata:
  name: db-user
  namespace: smartlogix
  labels:
    app.kubernetes.io/name: db-user
    app.kubernetes.io/part-of: smartlogix
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: db-user
  ports:
    - name: pg
      port: 5432
      targetPort: pg
