apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-user
  namespace: smartlogix
  labels:
    app.kubernetes.io/name: ms-user
    app.kubernetes.io/part-of: smartlogix
    app.kubernetes.io/component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ms-user
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ms-user
        app.kubernetes.io/part-of: smartlogix
        app.kubernetes.io/component: backend
    spec:
      containers:
        - name: ms-user
          image: smartlogix/ms-user:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: POSTGRES_USUARIO_DB
              valueFrom:
                configMapKeyRef:
                  name: smartlogix-config
                  key: POSTGRES_USUARIO_DB
            - name: SERVER_PORT
              value: "8080"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://db-user:5432/$(POSTGRES_USUARIO_DB)
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: smartlogix-config
                  key: POSTGRES_USUARIO_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smartlogix-secret
                  key: POSTGRES_USUARIO_PASSWORD
          resources:
            requests:
              cpu: 100m
              memory: 384Mi
            limits:
              cpu: 1000m
              memory: 768Mi
