spring.application.name=inventario
server.port=${SERVER_PORT:8080}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db-inventario
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: true

    properties:
      hibernate:
        format_sql: true

server:
  port: 8081