apiVersion: v1
kind: Service
metadata:
  name: ms-auth
  namespace: smartlogix
  labels:
    app.kubernetes.io/name: ms-auth
    app.kubernetes.io/part-of: smartlogix
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ms-auth
  ports:
    - name: http
      port: 8081
      targetPort: http
